title: <p align="center"> Nalini kanta</p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="">LinkedIn</a> |
  <a href="https://github.com/prince-06">GitHub</a>
  
  <br>   
  I'm working as a Specialist on BOSCH. I have nearly 7 year of experience in development profile using languagge like Java, Python.
  Also handing the Team here.
  Working in various domain like telecom,automotive etc.
  <br>
  </p>



theme: jekyll-theme-minimal
